Preparing test test_two_long_wait_validate_false_with_revert_exception
OperationNumber: Op1
Dependencies: 0
MaxRetries: 0
NumberOfFailures: 0
CallDelays: empty
RetryDelay: 0
RevertMaxRetries: 0
RevertNumberOfFailures: 0
RevertCallDelay: empty
RevertRetryDelay: 0
ValidateFunctionResults: empty
RevertValidateFunctionResults: empty
CallCounter: 0
RevertCallCounter: 0
ValidateCallCounter: 0
RevertValidateCallCounter: 0
Deactivate: empty
ThrowException: empty
ValidateThrowException: empty
RevertThrowException: empty
RevertValidateThrowException: empty
HasReportFail: False
HasRevert: False
HasValidate: False
HasRevertValidate: False

OperationNumber: Op2
Dependencies: 0
MaxRetries: 1
NumberOfFailures: 2
CallDelay: 1 - 5
CallDelay: 2 - 5
RetryDelay: 2
RevertMaxRetries: 2
RevertNumberOfFailures: 3
RevertCallDelay: empty
RevertRetryDelay: 2
ValidateFunctionResult: 1 - False
ValidateFunctionResult: 2 - False
RevertValidateFunctionResults: empty
CallCounter: 0
RevertCallCounter: 0
ValidateCallCounter: 0
RevertValidateCallCounter: 0
Deactivate: empty
ThrowException: empty
ValidateThrowException: empty
RevertThrowException: empty
RevertValidateThrowException: 1
RevertValidateThrowException: 2
HasReportFail: False
HasRevert: True
HasValidate: True
HasRevertValidate: False

Calling Op1: Success True
Calling Op2: Success False
Op2 Validate returns False
Calling Op2: Success False
Op2 Validate returns False
Calling revert for Op2: Success False
Calling revert for Op2: Success False
Calling revert for Op2: Success False
OnFailedRevertedCallback: FailedReverted.
Run Log:
[*time*][Op1]: Start Executing Op1
[*time*][Op1]: Op1 Success
[*time*][Op2]: Start Executing Op2
[*time*][Op2]: Registering reminder Op2:Retry for Op2 with interval 00:00:02
[*time*][Op2]: Wake by a reminder
[*time*][Op2]: The validate function does not exist or raised an exception, retry Op2 action
[*time*][Op2]: Retry Op2. Retry count: 1
[*time*][Op2]: Start Executing Op2
[*time*][Op2]: Registering reminder Op2:Retry for Op2 with interval 00:00:02
[*time*][Op2]: Wake by a reminder
[*time*][Op2]: The validate function does not exist or raised an exception, retry Op2 action
[*time*][Op2]: Op2 Failed. Retries exhausted.
[*time*][Op1]: Start Executing Revert Op1
[*time*][Op1]: No undo operation for Op1. Marking as reverted
[*time*][Op2]: Start Executing Revert Op2
[*time*][Op2]: Registering reminder Op2:Retry for Revert Op2 with interval 00:00:02
[*time*][Op2]: Retry Revert Op2. Retry count: 1
[*time*][Op2]: Start Executing Revert Op2
[*time*][Op2]: Registering reminder Op2:Retry for Revert Op2 with interval 00:00:02
[*time*][Op2]: Retry Revert Op2. Retry count: 2
[*time*][Op2]: Start Executing Revert Op2
[*time*][Op2]: Registering reminder Op2:Retry for Revert Op2 with interval 00:00:02
[*time*][Op2]: Revert Op2 Failed. Retries exhausted.


OnSagaCompleted: Id: test Status: RevertFailed

*** Telemetry ***
1: StartSaga - SagaID: test, Type: SagaOperations
2: StartOperation - SagaID: test, Operation: Op1
3: EndOperation - SagaID: test, Operation: Op1, Outcome: Succeeded
4: StartOperation - SagaID: test, Operation: Op2
5: RetryAttempt - SagaID: test, Operation: Op2, Attempt: 1
6: StartOperation - SagaID: test, Operation: Op2
7: EndOperation - SagaID: test, Operation: Op2, Outcome: Failed
8: StartOperation - SagaID: test, Operation: RevertOp2
9: RetryAttempt - SagaID: test, Operation: RevertOp2, Attempt: 1
10: StartOperation - SagaID: test, Operation: RevertOp2
11: RetryAttempt - SagaID: test, Operation: RevertOp2, Attempt: 2
12: StartOperation - SagaID: test, Operation: RevertOp2
13: EndOperation - SagaID: test, Operation: RevertOp2, Outcome: RevertFailed
14: EndSaga - SagaID: test, Outcome: PartiallyReverted
