Preparing test test_two_throw_exception_and_retry
OperationNumber: Op1
Dependencies: 0
MaxRetries: 1
NumberOfFailures: 0
CallDelays: empty
RetryDelay: 2
RevertMaxRetries: 0
RevertNumberOfFailures: 0
RevertCallDelay: empty
RevertRetryDelay: 0
ValidateFunctionResults: empty
RevertValidateFunctionResults: empty
CallCounter: 0
RevertCallCounter: 0
ValidateCallCounter: 0
RevertValidateCallCounter: 0
Deactivate: empty
ThrowException: 1
ValidateThrowException: empty
RevertThrowException: empty
RevertValidateThrowException: empty
HasReportFail: False
HasRevert: False
HasValidate: False
HasRevertValidate: False

OperationNumber: Op2
Dependencies: 0
MaxRetries: 1
NumberOfFailures: 0
CallDelays: empty
RetryDelay: 4
RevertMaxRetries: 0
RevertNumberOfFailures: 0
RevertCallDelay: empty
RevertRetryDelay: 0
ValidateFunctionResults: empty
RevertValidateFunctionResults: empty
CallCounter: 0
RevertCallCounter: 0
ValidateCallCounter: 0
RevertValidateCallCounter: 0
Deactivate: empty
ThrowException: 1
ValidateThrowException: empty
RevertThrowException: empty
RevertValidateThrowException: empty
HasReportFail: False
HasRevert: False
HasValidate: False
HasRevertValidate: False

OnRevertedCallback: Reverted.
Run Log:
[*time*][Op1]: Start Executing Op1
[*time*][Op1]: Registering reminder Op1:Retry for Op1 with interval 00:00:02
[*time*][Op1]: Error when calling Op1. Error: Throwing exception on call 1. Retry in 00:00:02 seconds
[*time*][Op2]: Start Executing Op2
[*time*][Op2]: Registering reminder Op2:Retry for Op2 with interval 00:00:04
[*time*][Op2]: Error when calling Op2. Error: Throwing exception on call 1. Retry in 00:00:04 seconds
[*time*][Op1]: Wake by a reminder
[*time*][Op1]: The validate function does not exist or raised an exception, retry Op1 action
[*time*][Op1]: Retry Op1. Retry count: 1
[*time*][Op1]: Registering reminder Op1:Retry for Op1 with configured interval of 00:00:02, waiting the 00:00:00 remaining seconds
[*time*][Op1]: Wake by a reminder
[*time*][Op1]: The validate function does not exist or raised an exception, retry Op1 action
[*time*][Op1]: Op1 Failed. Retries exhausted.
[*time*][Op1]: Start Executing Revert Op1
[*time*][Op1]: No undo operation for Op1. Marking as reverted
[*time*][Op2]: Start Executing Revert Op2
[*time*][Op2]: No undo operation for Op2. Marking as reverted


OnSagaCompleted: Id: test Status: Reverted

*** Telemetry ***
1: StartSaga - SagaID: test, Type: SagaOperations
2: StartOperation - SagaID: test, Operation: Op1
3: Exception - SagaID: test, Context: Error when calling Op1, Exception: Throwing exception on call 1
4: StartOperation - SagaID: test, Operation: Op2
5: Exception - SagaID: test, Context: Error when calling Op2, Exception: Throwing exception on call 1
6: EndOperation - SagaID: test, Operation: Op1, Outcome: Failed
7: EndSaga - SagaID: test, Outcome: Reverted
